config/routes.rb
MegaballWeb::Application.routes.draw do

  get "fb_auth/index"

  get "minimissions/index"
  get "news/index"
  get "bank/index"

  mount RailsAdmin::Engine => '/supper_hidden_admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" },  :skip => [:sessions]
  as :user do
    get 'signin'                  => 'devise/sessions#new', :as => :new_user_session
    post 'signin'                 => 'devise/sessions#create', :as => :user_session
    delete 'signout'              => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  match 'stats_test' => 'game#stats_test', :via => [:post]
  
  match 'tokens/create(.:any)' => 'tokens#create', :via => [:post], :defaults => {:format => 'json'}
  match 'map/:id'              => 'resource#map', :via => [:get], :defaults => {:format => 'json'}
  match 'ball/:id'             => 'resource#ball', :via => [:get], :defaults => {:format => 'json'}
  match 'game_event/:id'       => 'resource#game_event', :via => [:get], :defaults => {:format => 'json'}
  match 'animation/:id'        => 'resource#animation', :via => [:get], :defaults => {:format => 'json'}
  match 'users/:_id'           => 'users#show', :via => [:get] , :defaults => {:format => 'json'}
  match 'users'                => 'users#users', :via => [:get] , :defaults => {:format => 'json'}
  match 'user'                 => 'users#current', :via => [:get] , :defaults => {:format => 'json'}
  match 'user'                 => 'users#update', :via => [:post, :put, :patch] , :defaults => {:format => 'json'}
  match 'user_default'         => 'users#user_default', :via => [:get] , :defaults => {:format => 'json'}
  match 'user_items'           => 'users#user_items', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/refresh'         => 'users#refresh', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/check_first_prise' => 'users#check_first_prise', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/balance'         => 'users#balance', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/achievements'    => 'users#achievements', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/collections'     => 'users#collections', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/results'         => 'users#results', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/improve/:stat'   => 'users#improve', :via => [:post] , :defaults => {:format => 'json'}
  match 'user/messages'        => 'users#messages', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/check_weapons'   => 'users#check_weapons', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/read_message/:id'=> 'users#read_message', :via => [:post] , :defaults => {:format => 'json'}
  match 'user/ratings/:type'   => 'users#ratings', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/achievements'    => 'users#achievements', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/statistics'      => 'users#statistics', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/statistics/:id'  => 'users#statistics_by_id', :via => [:get] , :defaults => {:format => 'json'}
  match 'user/news'            => 'users#news', :via => [:get], :defaults => {:format => 'json'}
  match 'weapons/active'       => 'resource#weapons_active', :via => [:get] , :defaults => {:format => 'json'}
  match 'game_play/:id'        => 'resource#game_play', :via => [:get], :defaults => {:format => 'json'}
  match 'game_plays'           => 'resource#game_plays', :via => [:get], :defaults => {:format => 'json'}
  match 'complete_game_play/:id' => 'resource#complete_game_play', :via => [:get], :defaults => {:format => 'json'}
  match 'rooms/train'          => 'room#train', :via => [:get], :defaults => {:format => 'json'}
  match 'rooms/fast'           => 'room#fast', :via => [:get], :defaults => {:format => 'json'}
  match 'rooms/arena'           => 'room#arena', :via => [:get], :defaults => {:format => 'json'}
  match 'rooms/check_password' => 'room#check_password', :via => [:get], :defaults => {:format => 'json'}
  match 'save_log'             => 'users#save_log', :via => [:post], :defaults => {:format => 'json'}

  match 'uploader/avatar'      => 'uploader#avatar', :via => [:post], :defaults => {:format => 'json'}
  match 'uploader/mailru_avatar'      => 'uploader#mailru_avatar', :via => [:post], :defaults => {:format => 'json'}
  
  match 'super_hidden_route/user_stats/mau' => 'user_stats#mau', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/msau' => 'user_stats#msau', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/dau' => 'user_stats#dau', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/dmau' => 'user_stats#dau_mau', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/uret' => 'user_stats#users_retention', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/dconv' => 'user_stats#daily_conversion', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/mconv' => 'user_stats#monthly_conversion', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/arppu' => 'user_stats#arppu', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/sharks' => 'user_stats#sharks', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/opc' => 'user_stats#orders_per_category', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/purchase' => 'user_stats#purchase', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/faces_purchase' => 'user_stats#faces_purchase', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats' => 'user_stats#index', via: [:get], defaults: {format: 'html'}
  match 'super_hidden_route/user_stats/level_money_dependency' => 'user_stats#level_money_dependency', :via => [:get], :defaults => {:format => 'json'}
  match 'super_hidden_route/user_stats/level_money_dependency_average' => 'user_stats#level_money_dependency_average', :via => [:get], :defaults => {:format => 'json'}
  
  match 'servers/game_servers(.:any)' => 'servers#game_server_list', via: [:get], defaults: {format: 'json'}
  match 'servers/club_chat_server(.:any)' => 'servers#club_chat_server', via: [:get], defaults: {format: 'json'}

  match 'logs/game_server'  => 'logs#game_server',  via: [:get], defaults: {format: 'html'}
  match 'logs/policy'       => 'logs#policy', via: [:get], defaults: {format: 'html'}
  match 'logs/event'        => 'logs#event', via: [:get], defaults: {format: 'html'}
  match 'logs/web_server'   => 'logs#web_server', via: [:get], defaults: {format: 'html'}
  match 'logs/chat_server'  => 'logs#chat_server', via: [:get], defaults: {format: 'html'}
  match 'logs/users'        => 'logs#users', via: [:get], defaults: {format: 'html'}
  match 'mb'                => 'mb#index', via: [:get]
  match 'maps'              => 'mb#maps', via: [:get]
  match 'map/:id'           => 'mb#map', via: [:post]
  match 'mb/save'           => 'mb#save', via: [:post]

  match 'invites/check'    => 'invites#index', via: [:get]
  match 'invites/check'    => 'invites#check', via: [:post]
  match 'invites/generate' => 'invites#generate', via: [:post, :get]

  match 'store/items'             => 'store#items', via: [:get], defaults: {format: 'json'}
  match 'store/items/:_id'        => 'store#item', via: [:get], defaults: {format: 'json'}
  match 'store/items_and_weapons' => 'store#items_and_weapons', via: [:get], defaults: {format: 'json'}
  match 'store/buy'               => 'store#buy', via: [:put, :post], defaults: {format: 'json'}

  match 'club'             => 'clubs#show', :via => [:get], :defaults => {:format => 'json'}
  match 'club'             => 'clubs#update', :via => [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'club/all'         => 'clubs#all', :via => [:get, :post], :defaults => {:format => 'json'}
  match 'club/join/:cid'   => 'clubs#join', :via => [:post], :defaults => {:format => 'json'}
  match 'club/accept/:uid' => 'clubs#accept', :via => [:post], :defaults => {:format => 'json'}
  match 'club/reject/:uid' => 'clubs#reject', :via => [:post], :defaults => {:format => 'json'}
  match 'club/reject_all/' => 'clubs#reject_all', :via => [:post], :defaults => {:format => 'json'}
  match 'club/kick/:uid'   => 'clubs#kick', :via => [:post], :defaults => {:format => 'json'}
  match 'club/leave'       => 'clubs#leave', :via => [:post], :defaults => {:format => 'json'}
  match 'club/requests'    => 'clubs#show_requests', :via => [:get], :defaults => {:format => 'json'}
  match 'club/role/:uid'   => 'clubs#role', :via => [:post], :defaults => {:format => 'json'}
  match 'club/rename'      => 'clubs#rename', :via => [:post], :defaults => {:format => 'json'}
  match 'club/new'         => 'clubs#new_club', :via => [:post], :defaults => {:format => 'json'}
  match 'club/update_logo' => 'clubs#update_logo', :via => [:post], :defaults => {:format => 'json'}
  match 'club/upgrade'     => 'clubs#upgrade', :via => [:post], :defaults => {:format => 'json'}
  match 'club/user'        => 'clubs#user', :via => [:get], :defaults => {:format => 'json'}

  match 'energy/update_energy' => 'energy#update_energy', :via => [:get], :defaults => {:format => 'json'}

  match 'transfer/to_club' => 'transfers#to_club', :via => [:post], :defaults => {:format => 'json'}

  match 'roulette/items' => 'roulette#items', :via => [:get], :defaults => {:format => 'json'}
  match 'roulette/chest' => 'roulette#chest', :via => [:get], :defaults => {:format => 'json'}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MegaballWeb</title>
  <%= javascript_include_tag "application" %>

  <style type="text/css">
    body {
      min-width: <%= MEGABALL_CONFIG['window_wrapper']['width'] %>;
      background: url(<%= asset_path "/assets/without_sprite/back_outside#{params[:controller] == 'devise/sessions' ? '_auth' : ''}.png" %>) center -100px;
    }
  </style>
</head>
<body>

<% if !@iframe %>
  <!-- <div class="frame_wrapper"> -->
  <div class="main_wrapper" style="width:<%= MEGABALL_CONFIG['window_wrapper']['width'] %>;height:<%= MEGABALL_CONFIG['window_wrapper']['height']%>">
<% else %>
  <% if @current_provider == 'vk' %>
    <script type="text/javascript">
      vk_protocol = 'http:';

      if (document.location.protocol == 'https:')
        vk_protocol = 'https:';

      document.write('<script type="text\/javascript" src="' + vk_protocol + '//vk.com/js/api/xd_connection.js?2"><\/script>');
    </script>

    <script type="text/javascript">
      $(document).ready(function(){
        VK.init(function() { 
            window.MegaballWeb.VKInit();
          });
      });

      window.init_groups = true;
    </script>
  <% elsif @current_provider == 'ok' %>
    <div class="main_wrapper" style="width:<%= MEGABALL_CONFIG['window_wrapper']['width'] %>;height:<%= MEGABALL_CONFIG['window_wrapper']['height']%>">
    
    <script src="<%= params['api_server'] %>js/fapi.js" type="text/javascript"></script>


    <script type="text/javascript">
      $(document).ready(function(){
        //Initiatlize OK API
        FAPI.Client.initialize();
        
        window.social_service = new MegaballWeb.Social.OK
        window.payment_source = new MegaballWeb.Payment.OK

        FAPI.init('<%= params['api_server'] %>', '<%= request.query_string.html_safe %>',
          function(){ window.MegaballWeb.OkInit();}, 
          function(error){
             alert("API initialization failed");
        });

        //Callback function 
        function API_callback(method, result, data){
            alert("Method "+method+" finished with result "+result+", "+data);
        } 

      });

      window.init_groups = true;
    </script>

  <% elsif @current_provider == 'mailru' %>
    <script type="text/javascript" src="http://cdn.connect.mail.ru/js/loader.js"></script>
    
    <script type="text/javascript">
      $(document).ready(function(){
        mailru.loader.require('api', function() {
          mailru.app.init('<%= MEGABALL_IFRAME_CONFIG[@current_provider]['private_key'] %>');
          
          window.MegaballWeb.MailRuInit();
        });
      });

      window.init_groups = true;
    </script>
  <% end %>
<% end %>

<%= yield %>

<% if !@iframe or (@iframe and @current_provider == 'ok')%>
  <!-- </div> -->
</div>
<% end %>

<% if @iframe %>
<div class="navigation-help-wrapper">
<% end %>
  <div class="navigation-help">

  </div> 

<% if @iframe %>
</div>
<% end %>

<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter21522046 = new Ya.Metrika({id:21522046,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>

</body>
</html>

app/views/layouts/game.html.haml
!!!5
%html
  %head
    %title Мегабол: Футбол Онлайн
    %meta(name="title" content="Мегабол: Футбол Онлайн")
    %meta(name="description" content="Лучший футбол онлайн")
    = stylesheet_link_tag "game" 
    - if @iframe
      = stylesheet_link_tag "iframe" 
  %body
    = yield

app/views/layouts/logs.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Megaball: Log</title>
        <%= stylesheet_link_tag "logs/main", :media => "all" %>
        <script type="text/javascript">
            (function() {
                window.log_path = '<%= yield %>';
                window.lines_count = <%= get_positive_int_param 'lines', 20 %>;
            })();
        </script>
        <%= javascript_include_tag "jquery" %>
        <%= javascript_include_tag "logs/main" %>
    </head>
    <body>
        <div class="log" id="server_log">
        </div>

        <form>
            <div class="menu">
              <%= link_with_highlight "Game server", 'game_server' %>
              <%= link_with_highlight "Policy server", 'policy' %>
              <%= link_with_highlight "Event server", 'event' %>
              <%= link_with_highlight "Web server", 'web_server' %>
              <%= link_with_highlight "Chat server", 'chat_server' %>
              <%= link_with_highlight "Users", 'users' %>
                |
                Show last <input type="text" name="lines" id="count" value="<%= get_positive_int_param 'lines', 20 %>" /> lines
                <input type="submit" value="Submit" />
                |
                Auto scroll <input type="checkbox" id="auto_scroll" checked="checked" />
            </div>
        </form>
    </body>
</html>

app/views/layouts/map_builder.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>MapBuilder</title>
  <meta name="description" content="" />

  <%= javascript_include_tag "swfobject" %>
  <script>
    var flashvars = {
    };
    var params = {
      menu: "false",
      scale: "noScale",
      allowFullscreen: "true",
      allowScriptAccess: "always",
      bgcolor: "",
      wmode: "direct" // can cause issues with FP settings & webcam
    };
    var attributes = {
      id:"MapBuilder"
    };
    swfobject.embedSWF(
      "MapBuilder.swf", 
      "altContent", "100%", "100%", "10.0.0", 
      "expressInstall.swf", 
      flashvars, params, attributes);

    window.maps = [];

    <% Map.each do |map| %>
      window.maps.push(<%= map._id %>); 
    <% end %>

    window.SaveMap = function(data){
      $.ajax({url:'<%= mb_save_path %>',
                type:'POST',
                data:{map:data},
                success: function(data, status, jqXHR){
                  console.log(data);
                },
                error: function(jqXHR, status, errorThrown){
                  alert("Some error, status: " + status + " , error: " + errorThrown)
                }});
    }
  </script>
  <style>
    html, body { height:100%; overflow:hidden; }
    body { margin:0; }
  </style>
</head>
<body>
  <div id="altContent">
    <h1>MapBuilder</h1>
    <p><a href="http://www.adobe.com/go/getflashplayer">Get Adobe Flash player</a></p>
  </div>
</body>
</html>